### ISSUE TITLE
有线上的小程序可以参考效果吗?

### ISSUE THREAD

**Issue by zicjin** [zhixiaoqiang/taroCloud#2]
![image](https://user-images.githubusercontent.com/199482/68478249-686d3d80-026a-11ea-913d-2e7123186f28.png)
把dispatch.dispatchSetGlobalInfo()移除后:
![image](https://user-images.githubusercontent.com/199482/68478462-e2052b80-026a-11ea-90d6-46c256f260cf.png)
5个函数应该都已经上传:
![image](https://user-images.githubusercontent.com/199482/68478516-07923500-026b-11ea-8acf-8d987f67129e.png)

**Comment by zhixiaoqiang** [comment]
already fix， git pull
